---
- hosts: all
  become: yes
  tasks:
  - name: installing git
    apt:
      name: git
      state: present
      update_cache: yes
  - name: installing tree
    apt:
      name: git
      state: present
  - name: installing apache2
    apt:
      name: apache2 
      state: present


